# Use the official Golang image as a base image
FROM golang:1.21-alpine

# Set destination for COPY
WORKDIR /app

# Download Go modules
COPY go.mod go.sum ./
RUN go mod download

COPY *.go ./

# Set the environment variable
ENV APP_ENV=production

# Build the Go application
RUN CGO_ENABLED=0 GOOS=linux go build -o /user

# Run the tests in the container
RUN go test -v ./...

# Expose the port that your application will run on
EXPOSE 8082

# Command to run the executable
CMD ["/user"]